import { typeDefs } from './graphql-schema'
import { ApolloServer } from 'apollo-server-express'
import express from 'express'
import neo4j from 'neo4j-driver'
import { Neo4jGraphQL } from '@neo4j/graphql'
import dotenv from 'dotenv'

// set environment variables from .env
dotenv.config()
const app = express()

/*
 * Create a Neo4j driver instance to connect to the database
 * using credentials specified as environment variables
 * with fallback to defaults
 */
const driver = neo4j.driver(
  process.env.NEO4J_URI || 'bolt://localhost:7687',
  neo4j.auth.basic(
    process.env.NEO4J_USER || 'neo4j',
    process.env.NEO4J_PASSWORD || 'neo4j'
  )
)

const resolvers = {
  Query: {
    personaje: async (_parent, args, context, _info) => {
      const session = context.driver.session();
      const query = 'MATCH (p:Character) RETURN p';
      const result = await session.run(query);
      session.close();
      return result.records.map(record => record.get('p').properties);
    },
    comic: async (_parent, _args, context, _info) => {
      const session = context.driver.session();
      const query = 'MATCH (c:Comic) RETURN c';
      const result = await session.run(query);
      session.close();
      return result.records.map(record => record.get('c').properties);
    },
    escena: async (_parent, _args, context, _info) => {
      const session = context.driver.session();
      const query = 'MATCH (b:Event) RETURN b';
      const result = await session.run(query);
      session.close();
      return result.records.map(record => record.get('b').properties);
    },
    personajeDetalle: async (_parent, args, context, _info) => {
      const session = context.driver.session();
      const { name } = args;
      const query = 'MATCH (l:Character { name: $name }) RETURN l';
      const result = await session.run(query, { name });
      session.close();
      return result.records[0].get('l').properties;
    },
    escenaDetalle: async (_parent, args, context, _info) => {
      const session = context.driver.session();
      const { title } = args;
      const query = 'MATCH (l:Event { title: $tile }) RETURN l';
      const result = await session.run(query, { title });
      session.close();
      return result.records[0].get('l').properties;
    },
    escenaComic: async (_parent, args, context, _info) => {
      const session = context.driver.session();
      const { title } = args;
      const query = 'MATCH (l:Comic { title: $tile }) RETURN l';
      const result = await session.run(query, { title });
      session.close();
      return result.records[0].get('l').properties;
    },
  },
};

/*
 * Create an executable GraphQL schema object from GraphQL type definitions
 * including autogenerated queries and mutations.
 * Read more in the docs:
 * https://neo4j.com/docs/graphql-manual/current/
 */

/*
 * Create a new ApolloServer instance, serving the GraphQL schema
 * created using makeAugmentedSchema above and injecting the Neo4j driver
 * instance into the context object so it is available in the
 * generated resolvers to connect to the database.
 */


const server = new ApolloServer({
  context: {
    driver,
    driverConfig: { database: process.env.NEO4J_DATABASE || 'neo4j' },
  },
  typeDefs,
  resolvers,
  introspection: true,
  playground: true,
});

// Specify host, port and path for GraphQL endpoint
const port = process.env.GRAPHQL_SERVER_PORT || 4001
const path = process.env.GRAPHQL_SERVER_PATH || '/graphql'
const host = process.env.GRAPHQL_SERVER_HOST || 'localhost'

/*
 * Optionally, apply Express middleware for authentication, etc
 * This also also allows us to specify a path for the GraphQL endpoint
 */
server.applyMiddleware({ app, path })

app.listen({ host, port, path }, () => {
  console.log(`GraphQL server ready at http://${host}:${port}${path}`)
})
